workflows:
  ios-workflow:
    name: iOS Build
    environment:
      groups:
        - app_store_credentials # Your credentials group
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.example.litex" # Update with your bundle ID
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set up keychain
        script: keychain initialize

      - name: Fix iOS deployment target
        script: |
          cd ios
          # Update Podfile with platform 15.0
          if grep -q "platform :ios" Podfile; then
            sed -i '' 's/platform :ios, .*/platform :ios, "15.0"/' Podfile
          else
            echo 'platform :ios, "15.0"' > temp.txt
            cat Podfile >> temp.txt
            mv temp.txt Podfile
          fi

          # Update Xcode project deployment target
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 13.0/IPHONEOS_DEPLOYMENT_TARGET = 15.0/g' Runner.xcodeproj/project.pbxproj
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 14.0/IPHONEOS_DEPLOYMENT_TARGET = 15.0/g' Runner.xcodeproj/project.pbxproj

      - name: Fix Info.plist
        script: |
          cd ios/Runner
          # Convert to proper XML format
          plutil -convert xml1 Info.plist

      - name: Clean and install pods
        script: |
          cd ios
          pod deintegrate || true
          pod cache clean --all
          rm -rf Pods Podfile.lock
          pod repo update
          pod install --repo-update

      - name: Flutter setup
        script: |
          flutter clean
          flutter pub get

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign

      - name: Code signing
        script: |
          cd ios
          xcode-project use-profiles

      - name: Generate IPA
        script: |
          cd ios
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - your-email@example.com # Update with your email
        notify:
          success: true
          failure: true
