// Mocks generated by Mockito 5.4.6 from annotations
// in lite_x/test/settings/account_info_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fpdart/fpdart.dart' as _i5;
import 'package:lite_x/core/classes/AppFailure.dart' as _i20;
import 'package:lite_x/core/classes/PickedImage.dart' as _i17;
import 'package:lite_x/core/models/TokensModel.dart' as _i22;
import 'package:lite_x/core/models/usermodel.dart' as _i21;
import 'package:lite_x/features/auth/repositories/auth_local_repository.dart'
    as _i23;
import 'package:lite_x/features/auth/repositories/auth_remote_repository.dart'
    as _i19;
import 'package:lite_x/features/auth/view_model/auth_state.dart' as _i2;
import 'package:lite_x/features/auth/view_model/auth_view_model.dart' as _i15;
import 'package:lite_x/features/profile/models/create_reply_model.dart' as _i14;
import 'package:lite_x/features/profile/models/create_tweet_model.dart' as _i11;
import 'package:lite_x/features/profile/models/profile_model.dart' as _i7;
import 'package:lite_x/features/profile/models/profile_tweet_model.dart'
    as _i10;
import 'package:lite_x/features/profile/models/search_user_model.dart' as _i13;
import 'package:lite_x/features/profile/models/shared.dart' as _i6;
import 'package:lite_x/features/profile/models/tweet_reply_model.dart' as _i12;
import 'package:lite_x/features/profile/models/user_model.dart' as _i9;
import 'package:lite_x/features/profile/repositories/profile_repo.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i16;
import 'package:state_notifier/state_notifier.dart' as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthState_0 extends _i1.SmartFake implements _i2.AuthState {
  _FakeAuthState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepo extends _i1.Mock implements _i3.ProfileRepo {
  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.ProfileModel>> getProfileData(
    String? userName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileData, [userName]),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, _i7.ProfileModel>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, _i7.ProfileModel>>(
                    this,
                    Invocation.method(#getProfileData, [userName]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, _i7.ProfileModel>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, _i7.ProfileModel>>(
                    this,
                    Invocation.method(#getProfileData, [userName]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.ProfileModel>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>> getFollowers(
    String? userName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowers, [userName]),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, List<_i9.UserModel>>>(
                    this,
                    Invocation.method(#getFollowers, [userName]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, List<_i9.UserModel>>>(
                    this,
                    Invocation.method(#getFollowers, [userName]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>> getFollowings(
    String? userName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowings, [userName]),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, List<_i9.UserModel>>>(
                    this,
                    Invocation.method(#getFollowings, [userName]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, List<_i9.UserModel>>>(
                    this,
                    Invocation.method(#getFollowings, [userName]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>> getVerifiedFollowers(
    String? userName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getVerifiedFollowers, [userName]),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, List<_i9.UserModel>>>(
                    this,
                    Invocation.method(#getVerifiedFollowers, [userName]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, List<_i9.UserModel>>>(
                    this,
                    Invocation.method(#getVerifiedFollowers, [userName]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>> getFollowersYouKnow(
    String? userName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowersYouKnow, [userName]),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, List<_i9.UserModel>>>(
                    this,
                    Invocation.method(#getFollowersYouKnow, [userName]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, List<_i9.UserModel>>>(
                    this,
                    Invocation.method(#getFollowersYouKnow, [userName]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> followUser(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#followUser, [username]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#followUser, [username]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, void>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                    this,
                    Invocation.method(#followUser, [username]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> unFollowUser(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#unFollowUser, [username]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#unFollowUser, [username]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, void>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                    this,
                    Invocation.method(#unFollowUser, [username]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.ProfileModel>> updateProfile({
    required _i7.ProfileModel? newModel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {#newModel: newModel}),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, _i7.ProfileModel>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, _i7.ProfileModel>>(
                    this,
                    Invocation.method(#updateProfile, [], {
                      #newModel: newModel,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, _i7.ProfileModel>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, _i7.ProfileModel>>(
                    this,
                    Invocation.method(#updateProfile, [], {
                      #newModel: newModel,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.ProfileModel>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> blockUser(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#blockUser, [username]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#blockUser, [username]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, void>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                    this,
                    Invocation.method(#blockUser, [username]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> unBlockUser(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#unBlockUser, [username]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#unBlockUser, [username]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, void>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                    this,
                    Invocation.method(#unBlockUser, [username]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> muteUser(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#muteUser, [username]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#muteUser, [username]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, void>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                    this,
                    Invocation.method(#muteUser, [username]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> unMuteUser(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#unMuteUser, [username]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#unMuteUser, [username]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, void>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                    this,
                    Invocation.method(#unMuteUser, [username]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>> getMutedList(
    String? userName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMutedList, [userName]),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, List<_i9.UserModel>>>(
                    this,
                    Invocation.method(#getMutedList, [userName]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, List<_i9.UserModel>>>(
                    this,
                    Invocation.method(#getMutedList, [userName]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>> getBlockedList(
    String? userName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBlockedList, [userName]),
            returnValue:
                _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, List<_i9.UserModel>>>(
                    this,
                    Invocation.method(#getBlockedList, [userName]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, List<_i9.UserModel>>>(
                    this,
                    Invocation.method(#getBlockedList, [userName]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, List<_i9.UserModel>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> updateProfileBanner(
    String? userId,
    String? mediaId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfileBanner, [userId, mediaId]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#updateProfileBanner, [userId, mediaId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, void>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                    this,
                    Invocation.method(#updateProfileBanner, [userId, mediaId]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> updateProfilePhoto(
    String? userId,
    String? mediaId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfilePhoto, [userId, mediaId]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#updateProfilePhoto, [userId, mediaId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, void>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                    this,
                    Invocation.method(#updateProfilePhoto, [userId, mediaId]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i10.ProfileTweetModel>>>
  getProfilePosts(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#getProfilePosts, [username]),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.Failure, List<_i10.ProfileTweetModel>>
                >.value(
                  _i8.dummyValue<
                    _i5.Either<_i6.Failure, List<_i10.ProfileTweetModel>>
                  >(this, Invocation.method(#getProfilePosts, [username])),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i5.Either<_i6.Failure, List<_i10.ProfileTweetModel>>
                >.value(
                  _i8.dummyValue<
                    _i5.Either<_i6.Failure, List<_i10.ProfileTweetModel>>
                  >(this, Invocation.method(#getProfilePosts, [username])),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, List<_i10.ProfileTweetModel>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i10.ProfileTweetModel>>>
  getProfileLikes(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileLikes, [username]),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.Failure, List<_i10.ProfileTweetModel>>
                >.value(
                  _i8.dummyValue<
                    _i5.Either<_i6.Failure, List<_i10.ProfileTweetModel>>
                  >(this, Invocation.method(#getProfileLikes, [username])),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i5.Either<_i6.Failure, List<_i10.ProfileTweetModel>>
                >.value(
                  _i8.dummyValue<
                    _i5.Either<_i6.Failure, List<_i10.ProfileTweetModel>>
                  >(this, Invocation.method(#getProfileLikes, [username])),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, List<_i10.ProfileTweetModel>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> createTweet(
    _i11.CreateTweetModel? createTweetModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createTweet, [createTweetModel]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#createTweet, [createTweetModel]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, void>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                    this,
                    Invocation.method(#createTweet, [createTweetModel]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i12.TweetReplyModel>>>
  getTweetReplies(String? tweetId) =>
      (super.noSuchMethod(
            Invocation.method(#getTweetReplies, [tweetId]),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.Failure, List<_i12.TweetReplyModel>>
                >.value(
                  _i8.dummyValue<
                    _i5.Either<_i6.Failure, List<_i12.TweetReplyModel>>
                  >(this, Invocation.method(#getTweetReplies, [tweetId])),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i5.Either<_i6.Failure, List<_i12.TweetReplyModel>>
                >.value(
                  _i8.dummyValue<
                    _i5.Either<_i6.Failure, List<_i12.TweetReplyModel>>
                  >(this, Invocation.method(#getTweetReplies, [tweetId])),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, List<_i12.TweetReplyModel>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> deleteTweet(String? tweetId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTweet, [tweetId]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#deleteTweet, [tweetId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, void>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                    this,
                    Invocation.method(#deleteTweet, [tweetId]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, List<_i13.SearchUserModel>>>
  profileCurrentSearch(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#profileCurrentSearch, [query]),
            returnValue:
                _i4.Future<
                  _i5.Either<_i6.Failure, List<_i13.SearchUserModel>>
                >.value(
                  _i8.dummyValue<
                    _i5.Either<_i6.Failure, List<_i13.SearchUserModel>>
                  >(this, Invocation.method(#profileCurrentSearch, [query])),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i5.Either<_i6.Failure, List<_i13.SearchUserModel>>
                >.value(
                  _i8.dummyValue<
                    _i5.Either<_i6.Failure, List<_i13.SearchUserModel>>
                  >(this, Invocation.method(#profileCurrentSearch, [query])),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, List<_i13.SearchUserModel>>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> likeTweet(String? tweetId) =>
      (super.noSuchMethod(
            Invocation.method(#likeTweet, [tweetId]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#likeTweet, [tweetId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, void>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                    this,
                    Invocation.method(#likeTweet, [tweetId]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> unLikeTweet(String? tweetId) =>
      (super.noSuchMethod(
            Invocation.method(#unLikeTweet, [tweetId]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#unLikeTweet, [tweetId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, void>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                    this,
                    Invocation.method(#unLikeTweet, [tweetId]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> saveTweet(String? tweetId) =>
      (super.noSuchMethod(
            Invocation.method(#saveTweet, [tweetId]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#saveTweet, [tweetId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, void>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                    this,
                    Invocation.method(#saveTweet, [tweetId]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> unSaveTweet(String? tweetId) =>
      (super.noSuchMethod(
            Invocation.method(#unSaveTweet, [tweetId]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#unSaveTweet, [tweetId]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, void>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                    this,
                    Invocation.method(#unSaveTweet, [tweetId]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> replyOnTweet(
    String? tweetId,
    _i14.CreateReplyModel? createreplyModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#replyOnTweet, [tweetId, createreplyModel]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#replyOnTweet, [tweetId, createreplyModel]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, void>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                    this,
                    Invocation.method(#replyOnTweet, [
                      tweetId,
                      createreplyModel,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> changeEmailProfile(
    String? newEmail,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeEmailProfile, [newEmail]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#changeEmailProfile, [newEmail]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, void>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                    this,
                    Invocation.method(#changeEmailProfile, [newEmail]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> verifyChangeEmailProfile(
    String? newEmail,
    String? code,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyChangeEmailProfile, [newEmail, code]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#verifyChangeEmailProfile, [newEmail, code]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, void>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                    this,
                    Invocation.method(#verifyChangeEmailProfile, [
                      newEmail,
                      code,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i5.Either<_i6.Failure, void>> changePasswordProfile(
    String? oldPassword,
    String? newPassword,
    String? confirmNewPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePasswordProfile, [
              oldPassword,
              newPassword,
              confirmNewPassword,
            ]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, void>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                this,
                Invocation.method(#changePasswordProfile, [
                  oldPassword,
                  newPassword,
                  confirmNewPassword,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i6.Failure, void>>.value(
                  _i8.dummyValue<_i5.Either<_i6.Failure, void>>(
                    this,
                    Invocation.method(#changePasswordProfile, [
                      oldPassword,
                      newPassword,
                      confirmNewPassword,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, void>>);
}

/// A class which mocks [AuthViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthViewModel extends _i1.Mock implements _i15.AuthViewModel {
  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i16.Ref get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _i8.dummyValue<_i16.Ref>(
              this,
              Invocation.getter(#ref),
            ),
            returnValueForMissingStub: _i8.dummyValue<_i16.Ref>(
              this,
              Invocation.getter(#ref),
            ),
          )
          as _i16.Ref);

  @override
  _i2.AuthState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAuthState_0(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeAuthState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.AuthState);

  @override
  set state(_i2.AuthState? newState) => super.noSuchMethod(
    Invocation.setter(#state, newState),
    returnValueForMissingStub: null,
  );

  @override
  _i2.AuthState build() =>
      (super.noSuchMethod(
            Invocation.method(#build, []),
            returnValue: _FakeAuthState_0(this, Invocation.method(#build, [])),
            returnValueForMissingStub: _FakeAuthState_0(
              this,
              Invocation.method(#build, []),
            ),
          )
          as _i2.AuthState);

  @override
  _i4.Future<void> createAccount({
    required String? name,
    required String? email,
    required String? dateOfBirth,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAccount, [], {
              #name: name,
              #email: email,
              #dateOfBirth: dateOfBirth,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> verifySignupEmail({
    required String? email,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifySignupEmail, [], {
              #email: email,
              #code: code,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> finalizeSignup({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#finalizeSignup, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> uploadProfilePhoto(_i17.PickedImage? pickedImage) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePhoto, [pickedImage]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateUsername({required String? username}) =>
      (super.noSuchMethod(
            Invocation.method(#updateUsername, [], {#username: username}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveInterests(Set<String>? interests) =>
      (super.noSuchMethod(
            Invocation.method(#saveInterests, [interests]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> login({required String? email, required String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool?> validateEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#validateEmail, [email]),
            returnValue: _i4.Future<bool?>.value(),
            returnValueForMissingStub: _i4.Future<bool?>.value(),
          )
          as _i4.Future<bool?>);

  @override
  _i4.Future<void> checkEmail({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#checkEmail, [], {#email: email}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> forgetPassword({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [], {#email: email}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> verifyResetCode({
    required String? email,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [], {
              #email: email,
              #code: code,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resetPassword({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePassword({
    required String? password,
    required String? newpassword,
    required String? confirmPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [], {
              #password: password,
              #newpassword: newpassword,
              #confirmPassword: confirmPassword,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateEmail({required String? newEmail}) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmail, [], {#newEmail: newEmail}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> verifyNewEmail({
    required String? newEmail,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyNewEmail, [], {
              #newEmail: newEmail,
              #code: code,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void resetState() => super.noSuchMethod(
    Invocation.method(#resetState, []),
    returnValueForMissingStub: null,
  );

  @override
  void setAuthenticated() => super.noSuchMethod(
    Invocation.method(#setAuthenticated, []),
    returnValueForMissingStub: null,
  );

  @override
  void runBuild() => super.noSuchMethod(
    Invocation.method(#runBuild, []),
    returnValueForMissingStub: null,
  );

  @override
  _i18.RemoveListener listenSelf(
    void Function(_i2.AuthState?, _i2.AuthState)? listener, {
    void Function(Object, StackTrace)? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listenSelf, [listener], {#onError: onError}),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i18.RemoveListener);

  @override
  bool updateShouldNotify(_i2.AuthState? previous, _i2.AuthState? next) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [previous, next]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}

/// A class which mocks [AuthRemoteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteRepository extends _i1.Mock
    implements _i19.AuthRemoteRepository {
  @override
  _i4.Future<_i5.Either<_i20.AppFailure, String>> create({
    required String? name,
    required String? email,
    required String? dateOfBirth,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #name: name,
              #email: email,
              #dateOfBirth: dateOfBirth,
            }),
            returnValue: _i4.Future<_i5.Either<_i20.AppFailure, String>>.value(
              _i8.dummyValue<_i5.Either<_i20.AppFailure, String>>(
                this,
                Invocation.method(#create, [], {
                  #name: name,
                  #email: email,
                  #dateOfBirth: dateOfBirth,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i20.AppFailure, String>>.value(
                  _i8.dummyValue<_i5.Either<_i20.AppFailure, String>>(
                    this,
                    Invocation.method(#create, [], {
                      #name: name,
                      #email: email,
                      #dateOfBirth: dateOfBirth,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i20.AppFailure, String>>);

  @override
  _i4.Future<_i5.Either<_i20.AppFailure, String>> verifySignupEmail({
    required String? email,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifySignupEmail, [], {
              #email: email,
              #code: code,
            }),
            returnValue: _i4.Future<_i5.Either<_i20.AppFailure, String>>.value(
              _i8.dummyValue<_i5.Either<_i20.AppFailure, String>>(
                this,
                Invocation.method(#verifySignupEmail, [], {
                  #email: email,
                  #code: code,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i20.AppFailure, String>>.value(
                  _i8.dummyValue<_i5.Either<_i20.AppFailure, String>>(
                    this,
                    Invocation.method(#verifySignupEmail, [], {
                      #email: email,
                      #code: code,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i20.AppFailure, String>>);

  @override
  _i4.Future<_i5.Either<_i20.AppFailure, (_i21.UserModel, _i22.TokensModel)>>
  signup({required String? email, required String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i4.Future<
                  _i5.Either<
                    _i20.AppFailure,
                    (_i21.UserModel, _i22.TokensModel)
                  >
                >.value(
                  _i8.dummyValue<
                    _i5.Either<
                      _i20.AppFailure,
                      (_i21.UserModel, _i22.TokensModel)
                    >
                  >(
                    this,
                    Invocation.method(#signup, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i5.Either<
                    _i20.AppFailure,
                    (_i21.UserModel, _i22.TokensModel)
                  >
                >.value(
                  _i8.dummyValue<
                    _i5.Either<
                      _i20.AppFailure,
                      (_i21.UserModel, _i22.TokensModel)
                    >
                  >(
                    this,
                    Invocation.method(#signup, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i5.Either<_i20.AppFailure, (_i21.UserModel, _i22.TokensModel)>
          >);

  @override
  _i4.Future<_i5.Either<_i20.AppFailure, String>> uploadProfilePhoto({
    required _i17.PickedImage? pickedImage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePhoto, [], {
              #pickedImage: pickedImage,
            }),
            returnValue: _i4.Future<_i5.Either<_i20.AppFailure, String>>.value(
              _i8.dummyValue<_i5.Either<_i20.AppFailure, String>>(
                this,
                Invocation.method(#uploadProfilePhoto, [], {
                  #pickedImage: pickedImage,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i20.AppFailure, String>>.value(
                  _i8.dummyValue<_i5.Either<_i20.AppFailure, String>>(
                    this,
                    Invocation.method(#uploadProfilePhoto, [], {
                      #pickedImage: pickedImage,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i20.AppFailure, String>>);

  @override
  _i4.Future<_i5.Either<_i20.AppFailure, (_i21.UserModel, _i22.TokensModel)>>
  updateUsername({
    required _i21.UserModel? currentUser,
    required String? Username,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUsername, [], {
              #currentUser: currentUser,
              #Username: Username,
            }),
            returnValue:
                _i4.Future<
                  _i5.Either<
                    _i20.AppFailure,
                    (_i21.UserModel, _i22.TokensModel)
                  >
                >.value(
                  _i8.dummyValue<
                    _i5.Either<
                      _i20.AppFailure,
                      (_i21.UserModel, _i22.TokensModel)
                    >
                  >(
                    this,
                    Invocation.method(#updateUsername, [], {
                      #currentUser: currentUser,
                      #Username: Username,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i5.Either<
                    _i20.AppFailure,
                    (_i21.UserModel, _i22.TokensModel)
                  >
                >.value(
                  _i8.dummyValue<
                    _i5.Either<
                      _i20.AppFailure,
                      (_i21.UserModel, _i22.TokensModel)
                    >
                  >(
                    this,
                    Invocation.method(#updateUsername, [], {
                      #currentUser: currentUser,
                      #Username: Username,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i5.Either<_i20.AppFailure, (_i21.UserModel, _i22.TokensModel)>
          >);

  @override
  _i4.Future<_i5.Either<_i20.AppFailure, String>> registerFcmToken({
    required String? fcmToken,
    required String? osType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerFcmToken, [], {
              #fcmToken: fcmToken,
              #osType: osType,
            }),
            returnValue: _i4.Future<_i5.Either<_i20.AppFailure, String>>.value(
              _i8.dummyValue<_i5.Either<_i20.AppFailure, String>>(
                this,
                Invocation.method(#registerFcmToken, [], {
                  #fcmToken: fcmToken,
                  #osType: osType,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i20.AppFailure, String>>.value(
                  _i8.dummyValue<_i5.Either<_i20.AppFailure, String>>(
                    this,
                    Invocation.method(#registerFcmToken, [], {
                      #fcmToken: fcmToken,
                      #osType: osType,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i20.AppFailure, String>>);

  @override
  _i4.Future<_i5.Either<_i20.AppFailure, (_i21.UserModel, _i22.TokensModel)>>
  login({required String? email, required String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue:
                _i4.Future<
                  _i5.Either<
                    _i20.AppFailure,
                    (_i21.UserModel, _i22.TokensModel)
                  >
                >.value(
                  _i8.dummyValue<
                    _i5.Either<
                      _i20.AppFailure,
                      (_i21.UserModel, _i22.TokensModel)
                    >
                  >(
                    this,
                    Invocation.method(#login, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i5.Either<
                    _i20.AppFailure,
                    (_i21.UserModel, _i22.TokensModel)
                  >
                >.value(
                  _i8.dummyValue<
                    _i5.Either<
                      _i20.AppFailure,
                      (_i21.UserModel, _i22.TokensModel)
                    >
                  >(
                    this,
                    Invocation.method(#login, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i4.Future<
            _i5.Either<_i20.AppFailure, (_i21.UserModel, _i22.TokensModel)>
          >);

  @override
  _i4.Future<_i5.Either<_i20.AppFailure, bool>> check_email({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#check_email, [], {#email: email}),
            returnValue: _i4.Future<_i5.Either<_i20.AppFailure, bool>>.value(
              _i8.dummyValue<_i5.Either<_i20.AppFailure, bool>>(
                this,
                Invocation.method(#check_email, [], {#email: email}),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i20.AppFailure, bool>>.value(
                  _i8.dummyValue<_i5.Either<_i20.AppFailure, bool>>(
                    this,
                    Invocation.method(#check_email, [], {#email: email}),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i20.AppFailure, bool>>);

  @override
  _i4.Future<_i5.Either<_i20.AppFailure, String>> forget_password({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forget_password, [], {#email: email}),
            returnValue: _i4.Future<_i5.Either<_i20.AppFailure, String>>.value(
              _i8.dummyValue<_i5.Either<_i20.AppFailure, String>>(
                this,
                Invocation.method(#forget_password, [], {#email: email}),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i20.AppFailure, String>>.value(
                  _i8.dummyValue<_i5.Either<_i20.AppFailure, String>>(
                    this,
                    Invocation.method(#forget_password, [], {#email: email}),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i20.AppFailure, String>>);

  @override
  _i4.Future<_i5.Either<_i20.AppFailure, String>> verify_reset_code({
    required String? email,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verify_reset_code, [], {
              #email: email,
              #code: code,
            }),
            returnValue: _i4.Future<_i5.Either<_i20.AppFailure, String>>.value(
              _i8.dummyValue<_i5.Either<_i20.AppFailure, String>>(
                this,
                Invocation.method(#verify_reset_code, [], {
                  #email: email,
                  #code: code,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i20.AppFailure, String>>.value(
                  _i8.dummyValue<_i5.Either<_i20.AppFailure, String>>(
                    this,
                    Invocation.method(#verify_reset_code, [], {
                      #email: email,
                      #code: code,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i20.AppFailure, String>>);

  @override
  _i4.Future<_i5.Either<_i20.AppFailure, String>> reset_password({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reset_password, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<_i5.Either<_i20.AppFailure, String>>.value(
              _i8.dummyValue<_i5.Either<_i20.AppFailure, String>>(
                this,
                Invocation.method(#reset_password, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i20.AppFailure, String>>.value(
                  _i8.dummyValue<_i5.Either<_i20.AppFailure, String>>(
                    this,
                    Invocation.method(#reset_password, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i20.AppFailure, String>>);

  @override
  _i4.Future<_i5.Either<_i20.AppFailure, String>> update_password({
    required String? password,
    required String? newpassword,
    required String? confirmPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update_password, [], {
              #password: password,
              #newpassword: newpassword,
              #confirmPassword: confirmPassword,
            }),
            returnValue: _i4.Future<_i5.Either<_i20.AppFailure, String>>.value(
              _i8.dummyValue<_i5.Either<_i20.AppFailure, String>>(
                this,
                Invocation.method(#update_password, [], {
                  #password: password,
                  #newpassword: newpassword,
                  #confirmPassword: confirmPassword,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i20.AppFailure, String>>.value(
                  _i8.dummyValue<_i5.Either<_i20.AppFailure, String>>(
                    this,
                    Invocation.method(#update_password, [], {
                      #password: password,
                      #newpassword: newpassword,
                      #confirmPassword: confirmPassword,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i20.AppFailure, String>>);

  @override
  _i4.Future<_i5.Either<_i20.AppFailure, String>> update_email({
    required String? newemail,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update_email, [], {#newemail: newemail}),
            returnValue: _i4.Future<_i5.Either<_i20.AppFailure, String>>.value(
              _i8.dummyValue<_i5.Either<_i20.AppFailure, String>>(
                this,
                Invocation.method(#update_email, [], {#newemail: newemail}),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i20.AppFailure, String>>.value(
                  _i8.dummyValue<_i5.Either<_i20.AppFailure, String>>(
                    this,
                    Invocation.method(#update_email, [], {#newemail: newemail}),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i20.AppFailure, String>>);

  @override
  _i4.Future<_i5.Either<_i20.AppFailure, String>> verify_new_email({
    required String? newemail,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verify_new_email, [], {
              #newemail: newemail,
              #code: code,
            }),
            returnValue: _i4.Future<_i5.Either<_i20.AppFailure, String>>.value(
              _i8.dummyValue<_i5.Either<_i20.AppFailure, String>>(
                this,
                Invocation.method(#verify_new_email, [], {
                  #newemail: newemail,
                  #code: code,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i5.Either<_i20.AppFailure, String>>.value(
                  _i8.dummyValue<_i5.Either<_i20.AppFailure, String>>(
                    this,
                    Invocation.method(#verify_new_email, [], {
                      #newemail: newemail,
                      #code: code,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i5.Either<_i20.AppFailure, String>>);
}

/// A class which mocks [AuthLocalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalRepository extends _i1.Mock
    implements _i23.AuthLocalRepository {
  @override
  _i4.Future<void> saveUser(_i21.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [user]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearUser() =>
      (super.noSuchMethod(
            Invocation.method(#clearUser, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveTokens(_i22.TokensModel? tokens) =>
      (super.noSuchMethod(
            Invocation.method(#saveTokens, [tokens]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearTokens, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
