// Mocks generated by Mockito 5.4.6 from annotations
// in lite_x/test/settings/settings_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:lite_x/features/profile/models/shared.dart' as _i5;
import 'package:lite_x/features/profile/models/user_model.dart' as _i7;
import 'package:lite_x/features/settings/models/muted_users_response.dart'
    as _i8;
import 'package:lite_x/features/settings/models/settings_model.dart' as _i6;
import 'package:lite_x/features/settings/repositories/settings_repo.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SettingsRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepo extends _i1.Mock implements _i3.SettingsRepo {
  MockSettingsRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.SettingsModel>> getSettings(
    String? username,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSettings, [username]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.SettingsModel>>.value(
                  _FakeEither_0<_i5.Failure, _i6.SettingsModel>(
                    this,
                    Invocation.method(#getSettings, [username]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.SettingsModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.SettingsModel>> updateSettings({
    required _i6.SettingsModel? newModel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSettings, [], {#newModel: newModel}),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.SettingsModel>>.value(
                  _FakeEither_0<_i5.Failure, _i6.SettingsModel>(
                    this,
                    Invocation.method(#updateSettings, [], {
                      #newModel: newModel,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.SettingsModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>> getBlockedAccounts(
    String? username,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBlockedAccounts, [username]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i7.UserModel>>(
                    this,
                    Invocation.method(#getBlockedAccounts, [username]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>> getMutedAccounts(
    String? username,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMutedAccounts, [username]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i7.UserModel>>(
                    this,
                    Invocation.method(#getMutedAccounts, [username]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.MutedUsersResponse>>
  fetchMutedAccounts({int? limit = 30, String? cursor}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMutedAccounts, [], {
              #limit: limit,
              #cursor: cursor,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i8.MutedUsersResponse>
                >.value(
                  _FakeEither_0<_i5.Failure, _i8.MutedUsersResponse>(
                    this,
                    Invocation.method(#fetchMutedAccounts, [], {
                      #limit: limit,
                      #cursor: cursor,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.MutedUsersResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.MutedUsersResponse>>
  fetchBlockedAccounts({int? limit = 30, String? cursor}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBlockedAccounts, [], {
              #limit: limit,
              #cursor: cursor,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i8.MutedUsersResponse>
                >.value(
                  _FakeEither_0<_i5.Failure, _i8.MutedUsersResponse>(
                    this,
                    Invocation.method(#fetchBlockedAccounts, [], {
                      #limit: limit,
                      #cursor: cursor,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.MutedUsersResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> blockAccount(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#blockAccount, [username]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#blockAccount, [username]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> unblockAccount(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#unblockAccount, [username]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#unblockAccount, [username]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> muteAccount(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#muteAccount, [username]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#muteAccount, [username]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> unMuteAccount(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#unMuteAccount, [username]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#unMuteAccount, [username]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> followUser(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#followUser, [username]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#followUser, [username]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> unFollowUser(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#unFollowUser, [username]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#unFollowUser, [username]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
