// Mocks generated by Mockito 5.4.6 from annotations
// in lite_x/test/features/media/upload_media_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i7;

import 'package:dartz/dartz.dart' as _i2;
import 'package:lite_x/features/media/models/confirm_upload_model.dart' as _i8;
import 'package:lite_x/features/media/models/request_upload_model.dart' as _i6;
import 'package:lite_x/features/media/repository/media_repo.dart' as _i3;
import 'package:lite_x/features/profile/models/shared.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MediaRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockMediaRepo extends _i1.Mock implements _i3.MediaRepo {
  MockMediaRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.RequestUploadModel>> requestUpload(
    String? fileName,
    String? fileType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#requestUpload, [fileName, fileType]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.RequestUploadModel>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.RequestUploadModel>(
                    this,
                    Invocation.method(#requestUpload, [fileName, fileType]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.RequestUploadModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> upload(
    String? uploadUrl,
    _i7.File? mediaFile,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upload, [uploadUrl, mediaFile]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#upload, [uploadUrl, mediaFile]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.ConfirmUploadModel>> confirmUpload(
    String? keyName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#confirmUpload, [keyName]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i8.ConfirmUploadModel>
                >.value(
                  _FakeEither_0<_i5.Failure, _i8.ConfirmUploadModel>(
                    this,
                    Invocation.method(#confirmUpload, [keyName]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.ConfirmUploadModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> getMediaUrl(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMediaUrl, [id]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#getMediaUrl, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);
}
