// Mocks generated by Mockito 5.4.6 from annotations
// in lite_x/test/features/chat/view_model/conversations_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:lite_x/core/classes/AppFailure.dart' as _i5;
import 'package:lite_x/features/chat/models/conversationmodel.dart' as _i6;
import 'package:lite_x/features/chat/models/messagemodel.dart' as _i8;
import 'package:lite_x/features/chat/models/usersearchmodel.dart' as _i9;
import 'package:lite_x/features/chat/repositories/chat_local_repository.dart'
    as _i10;
import 'package:lite_x/features/chat/repositories/chat_remote_repository.dart'
    as _i2;
import 'package:lite_x/features/chat/repositories/socket_repository.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ChatRemoteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRemoteRepository extends _i1.Mock
    implements _i2.ChatRemoteRepository {
  MockChatRemoteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, _i6.ConversationModel>> create_chat({
    required List<String>? recipientIds,
    required String? Current_UserId,
    required bool? DMChat,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create_chat, [], {
              #recipientIds: recipientIds,
              #Current_UserId: Current_UserId,
              #DMChat: DMChat,
            }),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.AppFailure, _i6.ConversationModel>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.AppFailure, _i6.ConversationModel>
                  >(
                    this,
                    Invocation.method(#create_chat, [], {
                      #recipientIds: recipientIds,
                      #Current_UserId: Current_UserId,
                      #DMChat: DMChat,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.AppFailure, _i6.ConversationModel>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, List<_i8.MessageModel>>>
  getlastChatMessages(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getlastChatMessages, [chatId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.AppFailure, List<_i8.MessageModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.AppFailure, List<_i8.MessageModel>>
                  >(this, Invocation.method(#getlastChatMessages, [chatId])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.AppFailure, List<_i8.MessageModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, List<_i6.ConversationModel>>>
  getuserchats(String? Current_UserId) =>
      (super.noSuchMethod(
            Invocation.method(#getuserchats, [Current_UserId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.AppFailure, List<_i6.ConversationModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.AppFailure, List<_i6.ConversationModel>>
                  >(this, Invocation.method(#getuserchats, [Current_UserId])),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.AppFailure, List<_i6.ConversationModel>>
          >);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, List<_i8.MessageModel>>>
  getOlderMessagesChat({
    required String? chatId,
    required DateTime? lastMessageTimestamp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getOlderMessagesChat, [], {
              #chatId: chatId,
              #lastMessageTimestamp: lastMessageTimestamp,
            }),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.AppFailure, List<_i8.MessageModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.AppFailure, List<_i8.MessageModel>>
                  >(
                    this,
                    Invocation.method(#getOlderMessagesChat, [], {
                      #chatId: chatId,
                      #lastMessageTimestamp: lastMessageTimestamp,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.AppFailure, List<_i8.MessageModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, List<_i9.UserSearchModel>>> searchUsers(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.AppFailure, List<_i9.UserSearchModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.AppFailure, List<_i9.UserSearchModel>>
                  >(this, Invocation.method(#searchUsers, [query])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.AppFailure, List<_i9.UserSearchModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, _i6.ConversationModel>> getChatInfo(
    String? chatId,
    String? currentUserId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChatInfo, [chatId, currentUserId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.AppFailure, _i6.ConversationModel>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.AppFailure, _i6.ConversationModel>
                  >(
                    this,
                    Invocation.method(#getChatInfo, [chatId, currentUserId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.AppFailure, _i6.ConversationModel>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, String>> deleteChat(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChat, [chatId]),
            returnValue: _i3.Future<_i4.Either<_i5.AppFailure, String>>.value(
              _i7.dummyValue<_i4.Either<_i5.AppFailure, String>>(
                this,
                Invocation.method(#deleteChat, [chatId]),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.AppFailure, String>>);
}

/// A class which mocks [ChatLocalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatLocalRepository extends _i1.Mock
    implements _i10.ChatLocalRepository {
  MockChatLocalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i8.MessageModel> getCachedMessages(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedMessages, [chatId]),
            returnValue: <_i8.MessageModel>[],
          )
          as List<_i8.MessageModel>);

  @override
  _i3.Future<void> saveMessage(_i8.MessageModel? message) =>
      (super.noSuchMethod(
            Invocation.method(#saveMessage, [message]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveInitialMessages(List<_i8.MessageModel>? messages) =>
      (super.noSuchMethod(
            Invocation.method(#saveInitialMessages, [messages]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> replaceTempWithServerMessage({
    required String? tempId,
    required _i8.MessageModel? serverMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replaceTempWithServerMessage, [], {
              #tempId: tempId,
              #serverMessage: serverMessage,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markMessagesAsRead(String? chatId, String? myUserId) =>
      (super.noSuchMethod(
            Invocation.method(#markMessagesAsRead, [chatId, myUserId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markMessageAsSent(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#markMessageAsSent, [messageId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  List<_i8.MessageModel> getPendingMessages(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingMessages, [chatId]),
            returnValue: <_i8.MessageModel>[],
          )
          as List<_i8.MessageModel>);

  @override
  _i3.Future<void> upsertConversations(
    List<_i6.ConversationModel>? conversations,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upsertConversations, [conversations]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  List<_i6.ConversationModel> getAllConversations() =>
      (super.noSuchMethod(
            Invocation.method(#getAllConversations, []),
            returnValue: <_i6.ConversationModel>[],
          )
          as List<_i6.ConversationModel>);

  @override
  _i6.ConversationModel? getConversationById(String? id) =>
      (super.noSuchMethod(Invocation.method(#getConversationById, [id]))
          as _i6.ConversationModel?);

  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMessage(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [messageId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [conversationId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [SocketRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocketRepository extends _i1.Mock implements _i11.SocketRepository {
  MockSocketRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Ref get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _i7.dummyValue<_i12.Ref>(
              this,
              Invocation.getter(#ref),
            ),
          )
          as _i12.Ref);

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i3.Stream<Map<String, dynamic>> get messagesReadStream =>
      (super.noSuchMethod(
            Invocation.getter(#messagesReadStream),
            returnValue: _i3.Stream<Map<String, dynamic>>.empty(),
          )
          as _i3.Stream<Map<String, dynamic>>);

  @override
  _i3.Stream<Map<String, dynamic>> get newMessageStream =>
      (super.noSuchMethod(
            Invocation.getter(#newMessageStream),
            returnValue: _i3.Stream<Map<String, dynamic>>.empty(),
          )
          as _i3.Stream<Map<String, dynamic>>);

  @override
  _i3.Stream<Map<String, dynamic>> get messageAddedStream =>
      (super.noSuchMethod(
            Invocation.getter(#messageAddedStream),
            returnValue: _i3.Stream<Map<String, dynamic>>.empty(),
          )
          as _i3.Stream<Map<String, dynamic>>);

  @override
  _i3.Stream<Map<String, dynamic>> get typingStream =>
      (super.noSuchMethod(
            Invocation.getter(#typingStream),
            returnValue: _i3.Stream<Map<String, dynamic>>.empty(),
          )
          as _i3.Stream<Map<String, dynamic>>);

  @override
  _i3.Stream<Map<String, dynamic>> get unseenChatsStream =>
      (super.noSuchMethod(
            Invocation.getter(#unseenChatsStream),
            returnValue: _i3.Stream<Map<String, dynamic>>.empty(),
          )
          as _i3.Stream<Map<String, dynamic>>);

  @override
  void sendOpenMessageTab() => super.noSuchMethod(
    Invocation.method(#sendOpenMessageTab, []),
    returnValueForMissingStub: null,
  );

  @override
  void sendTyping(String? chatId, bool? isTyping) => super.noSuchMethod(
    Invocation.method(#sendTyping, [chatId, isTyping]),
    returnValueForMissingStub: null,
  );

  @override
  void onTyping(dynamic Function(dynamic)? callback) => super.noSuchMethod(
    Invocation.method(#onTyping, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  void sendMessage(Map<String, dynamic>? message) => super.noSuchMethod(
    Invocation.method(#sendMessage, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void onNewMessage(dynamic Function(dynamic)? callback) => super.noSuchMethod(
    Invocation.method(#onNewMessage, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  void openChat(String? chatId) => super.noSuchMethod(
    Invocation.method(#openChat, [chatId]),
    returnValueForMissingStub: null,
  );

  @override
  void onMessagesRead(dynamic Function(dynamic)? callback) =>
      super.noSuchMethod(
        Invocation.method(#onMessagesRead, [callback]),
        returnValueForMissingStub: null,
      );

  @override
  void onMessageAdded(dynamic Function(dynamic)? callback) =>
      super.noSuchMethod(
        Invocation.method(#onMessageAdded, [callback]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
