// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6-I0IOtAmC9jnyIxf9WruRMUuc_VJqFo',
    appId: '1:123824690535:web:5c24b3d2f16411d1960bc2',
    messagingSenderId: '123824690535',
    projectId: 'litex-3c6f1',
    authDomain: 'litex-3c6f1.firebaseapp.com',
    storageBucket: 'litex-3c6f1.firebasestorage.app',
    measurementId: 'G-V5P21GBW6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYiU34-5-Rr2nP_SHphvLSIiOyr4RuC8I',
    appId: '1:123824690535:android:fc6ea2d45764d44a960bc2',
    messagingSenderId: '123824690535',
    projectId: 'litex-3c6f1',
    storageBucket: 'litex-3c6f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANjGmgYBumwUsVg_BIBYsD0SN_BdEZfFg',
    appId: '1:123824690535:ios:7d4e4fe266a006fe960bc2',
    messagingSenderId: '123824690535',
    projectId: 'litex-3c6f1',
    storageBucket: 'litex-3c6f1.firebasestorage.app',
    iosClientId: '123824690535-5pta8j3mu07g0bb21n43n8q2vuulrstr.apps.googleusercontent.com',
    iosBundleId: 'com.example.litex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANjGmgYBumwUsVg_BIBYsD0SN_BdEZfFg',
    appId: '1:123824690535:ios:7d4e4fe266a006fe960bc2',
    messagingSenderId: '123824690535',
    projectId: 'litex-3c6f1',
    storageBucket: 'litex-3c6f1.firebasestorage.app',
    iosClientId: '123824690535-5pta8j3mu07g0bb21n43n8q2vuulrstr.apps.googleusercontent.com',
    iosBundleId: 'com.example.litex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6-I0IOtAmC9jnyIxf9WruRMUuc_VJqFo',
    appId: '1:123824690535:web:70728cc3cfda8de2960bc2',
    messagingSenderId: '123824690535',
    projectId: 'litex-3c6f1',
    authDomain: 'litex-3c6f1.firebaseapp.com',
    storageBucket: 'litex-3c6f1.firebasestorage.app',
    measurementId: 'G-ML4Y8SWB2Y',
  );
}
