// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5HN4nEV7xxsqLPufVptBwf2j-oXYVYCs',
    appId: '1:112144721859:web:cd55e199eb8ef04e813f76',
    messagingSenderId: '112144721859',
    projectId: 'psychic-fin-474008-h8',
    authDomain: 'psychic-fin-474008-h8.firebaseapp.com',
    storageBucket: 'psychic-fin-474008-h8.firebasestorage.app',
    measurementId: 'G-6XVXJKTZLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPqcctNBpWkQ-BKvYsHUEjvc_iwPBwsZ0',
    appId: '1:112144721859:android:227c69fccfe2ec4c813f76',
    messagingSenderId: '112144721859',
    projectId: 'psychic-fin-474008-h8',
    storageBucket: 'psychic-fin-474008-h8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwLkRHFcciSTzy8dGANfbWzmUQ4kEKhCM',
    appId: '1:112144721859:ios:990931c2c90bbd22813f76',
    messagingSenderId: '112144721859',
    projectId: 'psychic-fin-474008-h8',
    storageBucket: 'psychic-fin-474008-h8.firebasestorage.app',
    iosClientId: '112144721859-1i3tqk7isj7tf6733s8eje2fnj357k80.apps.googleusercontent.com',
    iosBundleId: 'com.example.litex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwLkRHFcciSTzy8dGANfbWzmUQ4kEKhCM',
    appId: '1:112144721859:ios:990931c2c90bbd22813f76',
    messagingSenderId: '112144721859',
    projectId: 'psychic-fin-474008-h8',
    storageBucket: 'psychic-fin-474008-h8.firebasestorage.app',
    iosClientId: '112144721859-1i3tqk7isj7tf6733s8eje2fnj357k80.apps.googleusercontent.com',
    iosBundleId: 'com.example.litex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5HN4nEV7xxsqLPufVptBwf2j-oXYVYCs',
    appId: '1:112144721859:web:01d0e76c4bc65596813f76',
    messagingSenderId: '112144721859',
    projectId: 'psychic-fin-474008-h8',
    authDomain: 'psychic-fin-474008-h8.firebaseapp.com',
    storageBucket: 'psychic-fin-474008-h8.firebasestorage.app',
    measurementId: 'G-7R40WH2L4T',
  );
}
