// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:lite_x/core/models/usermodel.dart';
import 'package:lite_x/features/chat/models/conversationmodel.dart';
import 'package:lite_x/features/chat/models/mediamodel.dart';
import 'package:lite_x/features/chat/models/messagemodel.dart';
import 'package:lite_x/features/home/models/tweet_model.dart';
import 'package:lite_x/features/home/models/user_profile_model.dart';
import 'package:lite_x/features/search/models/search_history_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ConversationModelAdapter());
    registerAdapter(MediaModelAdapter());
    registerAdapter(MediaModelAdapter());
    registerAdapter(MessageModelAdapter());
    registerAdapter(SearchHistoryHiveModelAdapter());
    registerAdapter(TweetModelAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(UserProfileModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ConversationModelAdapter());
    registerAdapter(MediaModelAdapter());
    registerAdapter(MediaModelAdapter());
    registerAdapter(MessageModelAdapter());
    registerAdapter(SearchHistoryHiveModelAdapter());
    registerAdapter(TweetModelAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(UserProfileModelAdapter());
  }
}
