// Manually created adapter for SearchHistoryHiveModel
// This normally would be generated by build_runner.

part of 'search_history_hive_model.dart';

class SearchHistoryHiveModelAdapter extends TypeAdapter<SearchHistoryHiveModel> {
  @override
  final int typeId = 3;

  @override
  SearchHistoryHiveModel read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{};
    for (var i = 0; i < numOfFields; i++) {
      final key = reader.readByte();
      fields[key] = reader.read();
    }
    return SearchHistoryHiveModel(
      query: fields[0] as String? ?? '',
      searchedAt: fields[1] as DateTime? ?? DateTime.now(),
    );
  }

  @override
  void write(BinaryWriter writer, SearchHistoryHiveModel obj) {
    writer
      ..writeByte(2)
      ..writeByte(0)
      ..write(obj.query)
      ..writeByte(1)
      ..write(obj.searchedAt);
  }
}
