// Mocks generated by Mockito 5.4.6 from annotations
// in lite_x/test/features/auth/view_model/auth_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i10;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:lite_x/core/classes/AppFailure.dart' as _i5;
import 'package:lite_x/core/classes/PickedImage.dart' as _i9;
import 'package:lite_x/core/models/TokensModel.dart' as _i7;
import 'package:lite_x/core/models/usermodel.dart' as _i6;
import 'package:lite_x/features/auth/repositories/auth_local_repository.dart'
    as _i11;
import 'package:lite_x/features/auth/repositories/auth_remote_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRemoteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteRepository extends _i1.Mock
    implements _i2.AuthRemoteRepository {
  MockAuthRemoteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>>
  loginWithGithub() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGithub, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>
                >.value(
                  _i8.dummyValue<
                    _i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>
                  >(this, Invocation.method(#loginWithGithub, [])),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>
          >);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>>
  signInWithGoogleAndroid() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogleAndroid, []),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>
                >.value(
                  _i8.dummyValue<
                    _i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>
                  >(this, Invocation.method(#signInWithGoogleAndroid, [])),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>
          >);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, String>> create({
    required String? name,
    required String? email,
    required String? dateOfBirth,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #name: name,
              #email: email,
              #dateOfBirth: dateOfBirth,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.AppFailure, String>>.value(
              _i8.dummyValue<_i4.Either<_i5.AppFailure, String>>(
                this,
                Invocation.method(#create, [], {
                  #name: name,
                  #email: email,
                  #dateOfBirth: dateOfBirth,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.AppFailure, String>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, String>> verifySignupEmail({
    required String? email,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifySignupEmail, [], {
              #email: email,
              #code: code,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.AppFailure, String>>.value(
              _i8.dummyValue<_i4.Either<_i5.AppFailure, String>>(
                this,
                Invocation.method(#verifySignupEmail, [], {
                  #email: email,
                  #code: code,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.AppFailure, String>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>>
  signup({required String? email, required String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#signup, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>
                >.value(
                  _i8.dummyValue<
                    _i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>
                  >(
                    this,
                    Invocation.method(#signup, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>
          >);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, Map<String, dynamic>>>
  uploadProfilePhoto({required _i9.PickedImage? pickedImage}) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfilePhoto, [], {
              #pickedImage: pickedImage,
            }),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.AppFailure, Map<String, dynamic>>
                >.value(
                  _i8.dummyValue<
                    _i4.Either<_i5.AppFailure, Map<String, dynamic>>
                  >(
                    this,
                    Invocation.method(#uploadProfilePhoto, [], {
                      #pickedImage: pickedImage,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.AppFailure, Map<String, dynamic>>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, _i10.File>> downloadMedia({
    required String? mediaId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#downloadMedia, [], {#mediaId: mediaId}),
            returnValue:
                _i3.Future<_i4.Either<_i5.AppFailure, _i10.File>>.value(
                  _i8.dummyValue<_i4.Either<_i5.AppFailure, _i10.File>>(
                    this,
                    Invocation.method(#downloadMedia, [], {#mediaId: mediaId}),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.AppFailure, _i10.File>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>>
  updateUsername({
    required _i6.UserModel? currentUser,
    required String? Username,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUsername, [], {
              #currentUser: currentUser,
              #Username: Username,
            }),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>
                >.value(
                  _i8.dummyValue<
                    _i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>
                  >(
                    this,
                    Invocation.method(#updateUsername, [], {
                      #currentUser: currentUser,
                      #Username: Username,
                    }),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>
          >);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, String>> setbirthdate({
    required String? day,
    required String? month,
    required String? year,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setbirthdate, [], {
              #day: day,
              #month: month,
              #year: year,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.AppFailure, String>>.value(
              _i8.dummyValue<_i4.Either<_i5.AppFailure, String>>(
                this,
                Invocation.method(#setbirthdate, [], {
                  #day: day,
                  #month: month,
                  #year: year,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.AppFailure, String>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, String>> registerFcmToken({
    required String? fcmToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerFcmToken, [], {#fcmToken: fcmToken}),
            returnValue: _i3.Future<_i4.Either<_i5.AppFailure, String>>.value(
              _i8.dummyValue<_i4.Either<_i5.AppFailure, String>>(
                this,
                Invocation.method(#registerFcmToken, [], {#fcmToken: fcmToken}),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.AppFailure, String>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>>
  login({required String? email, required String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>
                >.value(
                  _i8.dummyValue<
                    _i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>
                  >(
                    this,
                    Invocation.method(#login, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>
          >);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, bool>> check_email({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#check_email, [], {#email: email}),
            returnValue: _i3.Future<_i4.Either<_i5.AppFailure, bool>>.value(
              _i8.dummyValue<_i4.Either<_i5.AppFailure, bool>>(
                this,
                Invocation.method(#check_email, [], {#email: email}),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.AppFailure, bool>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, List<String>>> suggest_usernames({
    required String? username,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#suggest_usernames, [], {#username: username}),
            returnValue:
                _i3.Future<_i4.Either<_i5.AppFailure, List<String>>>.value(
                  _i8.dummyValue<_i4.Either<_i5.AppFailure, List<String>>>(
                    this,
                    Invocation.method(#suggest_usernames, [], {
                      #username: username,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.AppFailure, List<String>>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, String>> forget_password({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forget_password, [], {#email: email}),
            returnValue: _i3.Future<_i4.Either<_i5.AppFailure, String>>.value(
              _i8.dummyValue<_i4.Either<_i5.AppFailure, String>>(
                this,
                Invocation.method(#forget_password, [], {#email: email}),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.AppFailure, String>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, String>> verify_reset_code({
    required String? email,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verify_reset_code, [], {
              #email: email,
              #code: code,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.AppFailure, String>>.value(
              _i8.dummyValue<_i4.Either<_i5.AppFailure, String>>(
                this,
                Invocation.method(#verify_reset_code, [], {
                  #email: email,
                  #code: code,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.AppFailure, String>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>>
  reset_password({required String? email, required String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#reset_password, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>
                >.value(
                  _i8.dummyValue<
                    _i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>
                  >(
                    this,
                    Invocation.method(#reset_password, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i3.Future<
            _i4.Either<_i5.AppFailure, (_i6.UserModel, _i7.TokensModel)>
          >);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, String>> update_password({
    required String? password,
    required String? newpassword,
    required String? confirmPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update_password, [], {
              #password: password,
              #newpassword: newpassword,
              #confirmPassword: confirmPassword,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.AppFailure, String>>.value(
              _i8.dummyValue<_i4.Either<_i5.AppFailure, String>>(
                this,
                Invocation.method(#update_password, [], {
                  #password: password,
                  #newpassword: newpassword,
                  #confirmPassword: confirmPassword,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.AppFailure, String>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, String>> update_email({
    required String? newemail,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#update_email, [], {#newemail: newemail}),
            returnValue: _i3.Future<_i4.Either<_i5.AppFailure, String>>.value(
              _i8.dummyValue<_i4.Either<_i5.AppFailure, String>>(
                this,
                Invocation.method(#update_email, [], {#newemail: newemail}),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.AppFailure, String>>);

  @override
  _i3.Future<_i4.Either<_i5.AppFailure, String>> verify_new_email({
    required String? newemail,
    required String? code,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verify_new_email, [], {
              #newemail: newemail,
              #code: code,
            }),
            returnValue: _i3.Future<_i4.Either<_i5.AppFailure, String>>.value(
              _i8.dummyValue<_i4.Either<_i5.AppFailure, String>>(
                this,
                Invocation.method(#verify_new_email, [], {
                  #newemail: newemail,
                  #code: code,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Either<_i5.AppFailure, String>>);
}

/// A class which mocks [AuthLocalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalRepository extends _i1.Mock
    implements _i11.AuthLocalRepository {
  MockAuthLocalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i7.TokensModel?> get tokenStream =>
      (super.noSuchMethod(
            Invocation.getter(#tokenStream),
            returnValue: _i3.Stream<_i7.TokensModel?>.empty(),
          )
          as _i3.Stream<_i7.TokensModel?>);

  @override
  _i3.Future<void> saveUser(_i6.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [user]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearUser() =>
      (super.noSuchMethod(
            Invocation.method(#clearUser, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveTokens(_i7.TokensModel? tokens) =>
      (super.noSuchMethod(
            Invocation.method(#saveTokens, [tokens]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearTokens, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
