// Mocks generated by Mockito 5.4.6 from annotations
// in lite_x/test/features/profile/view_model/providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i8;
import 'package:lite_x/features/profile/models/create_reply_model.dart' as _i13;
import 'package:lite_x/features/profile/models/create_tweet_model.dart' as _i10;
import 'package:lite_x/features/profile/models/profile_model.dart' as _i6;
import 'package:lite_x/features/profile/models/profile_tweet_model.dart' as _i9;
import 'package:lite_x/features/profile/models/search_user_model.dart' as _i12;
import 'package:lite_x/features/profile/models/shared.dart' as _i5;
import 'package:lite_x/features/profile/models/tweet_reply_model.dart' as _i11;
import 'package:lite_x/features/profile/models/user_model.dart' as _i7;
import 'package:lite_x/features/profile/repositories/profile_repo.dart' as _i3;
import 'package:lite_x/features/trends/models/for_you_response_model.dart'
    as _i14;
import 'package:lite_x/features/trends/models/paginated_tweets.dart' as _i17;
import 'package:lite_x/features/trends/models/trend_category.dart' as _i15;
import 'package:lite_x/features/trends/models/trend_model.dart' as _i16;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepo extends _i1.Mock implements _i3.ProfileRepo {
  MockProfileRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileModel>> getProfileData(
    String? userName,
    String? currentUsername,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileData, [userName, currentUsername]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileModel>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ProfileModel>(
                    this,
                    Invocation.method(#getProfileData, [
                      userName,
                      currentUsername,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>> getFollowers(
    String? userName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowers, [userName]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i7.UserModel>>(
                    this,
                    Invocation.method(#getFollowers, [userName]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>> getFollowings(
    String? userName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowings, [userName]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i7.UserModel>>(
                    this,
                    Invocation.method(#getFollowings, [userName]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>> getVerifiedFollowers(
    String? userName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getVerifiedFollowers, [userName]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i7.UserModel>>(
                    this,
                    Invocation.method(#getVerifiedFollowers, [userName]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>> getFollowersYouKnow(
    String? userName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowersYouKnow, [userName]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i7.UserModel>>(
                    this,
                    Invocation.method(#getFollowersYouKnow, [userName]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> followUser(
    String? username,
    _i8.Ref? ref,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#followUser, [username, ref]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#followUser, [username, ref]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> unFollowUser(
    String? username,
    _i8.Ref? ref,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#unFollowUser, [username, ref]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#unFollowUser, [username, ref]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileModel>> updateProfile({
    required _i6.ProfileModel? newModel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {#newModel: newModel}),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileModel>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ProfileModel>(
                    this,
                    Invocation.method(#updateProfile, [], {
                      #newModel: newModel,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ProfileModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> blockUser(
    String? username,
    _i8.Ref? ref,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#blockUser, [username, ref]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#blockUser, [username, ref]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> unBlockUser(
    String? username,
    _i8.Ref? ref,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#unBlockUser, [username, ref]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#unBlockUser, [username, ref]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> muteUser(
    String? username,
    _i8.Ref? ref,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#muteUser, [username, ref]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#muteUser, [username, ref]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> unMuteUser(
    String? username,
    _i8.Ref? ref,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#unMuteUser, [username, ref]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#unMuteUser, [username, ref]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>> getMutedList(
    String? userName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMutedList, [userName]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i7.UserModel>>(
                    this,
                    Invocation.method(#getMutedList, [userName]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>> getBlockedList(
    String? userName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBlockedList, [userName]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i7.UserModel>>(
                    this,
                    Invocation.method(#getBlockedList, [userName]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateProfileBanner(
    String? userId,
    String? mediaId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfileBanner, [userId, mediaId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updateProfileBanner, [userId, mediaId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateProfilePhoto(
    String? userId,
    String? mediaId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfilePhoto, [userId, mediaId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updateProfilePhoto, [userId, mediaId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeBanner(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#removeBanner, [userId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#removeBanner, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.ProfileTweetModel>>>
  getProfilePosts(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#getProfilePosts, [username]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i9.ProfileTweetModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i9.ProfileTweetModel>>(
                    this,
                    Invocation.method(#getProfilePosts, [username]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i9.ProfileTweetModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.ProfileTweetModel>>>
  getMediaPosts(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#getMediaPosts, [username]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i9.ProfileTweetModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i9.ProfileTweetModel>>(
                    this,
                    Invocation.method(#getMediaPosts, [username]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i9.ProfileTweetModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.ProfileTweetModel>>>
  getProfileLikes(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileLikes, [username]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i9.ProfileTweetModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i9.ProfileTweetModel>>(
                    this,
                    Invocation.method(#getProfileLikes, [username]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i9.ProfileTweetModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.ProfileTweetModel>> getProfileTweet(
    String? tweetId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileTweet, [tweetId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i9.ProfileTweetModel>
                >.value(
                  _FakeEither_0<_i5.Failure, _i9.ProfileTweetModel>(
                    this,
                    Invocation.method(#getProfileTweet, [tweetId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i9.ProfileTweetModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> createTweet(
    _i10.CreateTweetModel? createTweetModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createTweet, [createTweetModel]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#createTweet, [createTweetModel]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i11.TweetReplyModel>>>
  getTweetReplies(String? tweetId) =>
      (super.noSuchMethod(
            Invocation.method(#getTweetReplies, [tweetId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i11.TweetReplyModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i11.TweetReplyModel>>(
                    this,
                    Invocation.method(#getTweetReplies, [tweetId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i11.TweetReplyModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteTweet(
    String? tweetId,
    _i8.Ref? ref,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTweet, [tweetId, ref]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteTweet, [tweetId, ref]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i12.SearchUserModel>>>
  profileCurrentSearch(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#profileCurrentSearch, [query]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i12.SearchUserModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i12.SearchUserModel>>(
                    this,
                    Invocation.method(#profileCurrentSearch, [query]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i12.SearchUserModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> likeTweet(
    String? tweetId,
    _i8.Ref? ref,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#likeTweet, [tweetId, ref]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#likeTweet, [tweetId, ref]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> unLikeTweet(
    String? tweetId,
    _i8.Ref? ref,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#unLikeTweet, [tweetId, ref]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#unLikeTweet, [tweetId, ref]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> saveTweet(String? tweetId) =>
      (super.noSuchMethod(
            Invocation.method(#saveTweet, [tweetId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#saveTweet, [tweetId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> unSaveTweet(String? tweetId) =>
      (super.noSuchMethod(
            Invocation.method(#unSaveTweet, [tweetId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#unSaveTweet, [tweetId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> replyOnTweet(
    String? tweetId,
    _i13.CreateReplyModel? createreplyModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#replyOnTweet, [tweetId, createreplyModel]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#replyOnTweet, [tweetId, createreplyModel]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> retweetProfileTweet(
    String? tweetId,
    _i8.Ref? ref,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#retweetProfileTweet, [tweetId, ref]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#retweetProfileTweet, [tweetId, ref]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteRetweetProfileTweet(
    String? tweetId,
    _i8.Ref? ref,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRetweetProfileTweet, [tweetId, ref]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteRetweetProfileTweet, [tweetId, ref]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> changeEmailProfile(
    String? newEmail,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeEmailProfile, [newEmail]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#changeEmailProfile, [newEmail]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> verifyChangeEmailProfile(
    String? newEmail,
    String? code,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyChangeEmailProfile, [newEmail, code]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#verifyChangeEmailProfile, [newEmail, code]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> changePasswordProfile(
    String? oldPassword,
    String? newPassword,
    String? confirmNewPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePasswordProfile, [
              oldPassword,
              newPassword,
              confirmNewPassword,
            ]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#changePasswordProfile, [
                  oldPassword,
                  newPassword,
                  confirmNewPassword,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i14.ForYouResponseModel>>
  getForYouTrends() =>
      (super.noSuchMethod(
            Invocation.method(#getForYouTrends, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i14.ForYouResponseModel>
                >.value(
                  _FakeEither_0<_i5.Failure, _i14.ForYouResponseModel>(
                    this,
                    Invocation.method(#getForYouTrends, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i14.ForYouResponseModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i15.TrendCategory>> getTrenCategory(
    String? catName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTrenCategory, [catName]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i15.TrendCategory>>.value(
                  _FakeEither_0<_i5.Failure, _i15.TrendCategory>(
                    this,
                    Invocation.method(#getTrenCategory, [catName]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i15.TrendCategory>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i16.TrendModel>>>
  getAvailableTrends() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableTrends, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i16.TrendModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i16.TrendModel>>(
                    this,
                    Invocation.method(#getAvailableTrends, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i16.TrendModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>> getWhoToFollow() =>
      (super.noSuchMethod(
            Invocation.method(#getWhoToFollow, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i7.UserModel>>(
                    this,
                    Invocation.method(#getWhoToFollow, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.UserModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.ProfileTweetModel>>>
  getTweetsForHashtag(String? hashtagId) =>
      (super.noSuchMethod(
            Invocation.method(#getTweetsForHashtag, [hashtagId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i9.ProfileTweetModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i9.ProfileTweetModel>>(
                    this,
                    Invocation.method(#getTweetsForHashtag, [hashtagId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i9.ProfileTweetModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i17.PaginatedTweets>>
  getTweetsForExploreCategory(String? categoryName, {String? cursor}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getTweetsForExploreCategory,
              [categoryName],
              {#cursor: cursor},
            ),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i17.PaginatedTweets>>.value(
                  _FakeEither_0<_i5.Failure, _i17.PaginatedTweets>(
                    this,
                    Invocation.method(
                      #getTweetsForExploreCategory,
                      [categoryName],
                      {#cursor: cursor},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i17.PaginatedTweets>>);
}
