// Mocks generated by Mockito 5.4.6 from annotations
// in lite_x/test/profile/mute_block_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fpdart/fpdart.dart' as _i4;
import 'package:lite_x/features/profile/models/create_reply_model.dart' as _i13;
import 'package:lite_x/features/profile/models/create_tweet_model.dart' as _i10;
import 'package:lite_x/features/profile/models/profile_model.dart' as _i6;
import 'package:lite_x/features/profile/models/profile_tweet_model.dart' as _i9;
import 'package:lite_x/features/profile/models/search_user_model.dart' as _i12;
import 'package:lite_x/features/profile/models/shared.dart' as _i5;
import 'package:lite_x/features/profile/models/tweet_reply_model.dart' as _i11;
import 'package:lite_x/features/profile/models/user_model.dart' as _i8;
import 'package:lite_x/features/profile/repositories/profile_repo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProfileRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepo extends _i1.Mock implements _i2.ProfileRepo {
  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.ProfileModel>> getProfileData(
    String? userName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileData, [userName]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.ProfileModel>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.ProfileModel>>(
                    this,
                    Invocation.method(#getProfileData, [userName]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, _i6.ProfileModel>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.ProfileModel>>(
                    this,
                    Invocation.method(#getProfileData, [userName]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.ProfileModel>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>> getFollowers(
    String? userName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowers, [userName]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i8.UserModel>>>(
                    this,
                    Invocation.method(#getFollowers, [userName]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i8.UserModel>>>(
                    this,
                    Invocation.method(#getFollowers, [userName]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>> getFollowings(
    String? userName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowings, [userName]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i8.UserModel>>>(
                    this,
                    Invocation.method(#getFollowings, [userName]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i8.UserModel>>>(
                    this,
                    Invocation.method(#getFollowings, [userName]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>> getVerifiedFollowers(
    String? userName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getVerifiedFollowers, [userName]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i8.UserModel>>>(
                    this,
                    Invocation.method(#getVerifiedFollowers, [userName]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i8.UserModel>>>(
                    this,
                    Invocation.method(#getVerifiedFollowers, [userName]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>> getFollowersYouKnow(
    String? userName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowersYouKnow, [userName]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i8.UserModel>>>(
                    this,
                    Invocation.method(#getFollowersYouKnow, [userName]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i8.UserModel>>>(
                    this,
                    Invocation.method(#getFollowersYouKnow, [userName]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> followUser(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#followUser, [username]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#followUser, [username]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#followUser, [username]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> unFollowUser(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#unFollowUser, [username]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#unFollowUser, [username]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#unFollowUser, [username]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.ProfileModel>> updateProfile({
    required _i6.ProfileModel? newModel,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {#newModel: newModel}),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, _i6.ProfileModel>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.ProfileModel>>(
                    this,
                    Invocation.method(#updateProfile, [], {
                      #newModel: newModel,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, _i6.ProfileModel>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, _i6.ProfileModel>>(
                    this,
                    Invocation.method(#updateProfile, [], {
                      #newModel: newModel,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, _i6.ProfileModel>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> blockUser(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#blockUser, [username]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#blockUser, [username]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#blockUser, [username]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> unBlockUser(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#unBlockUser, [username]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#unBlockUser, [username]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#unBlockUser, [username]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> muteUser(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#muteUser, [username]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#muteUser, [username]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#muteUser, [username]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> unMuteUser(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#unMuteUser, [username]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#unMuteUser, [username]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#unMuteUser, [username]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>> getMutedList(
    String? userName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMutedList, [userName]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i8.UserModel>>>(
                    this,
                    Invocation.method(#getMutedList, [userName]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i8.UserModel>>>(
                    this,
                    Invocation.method(#getMutedList, [userName]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>> getBlockedList(
    String? userName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBlockedList, [userName]),
            returnValue:
                _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i8.UserModel>>>(
                    this,
                    Invocation.method(#getBlockedList, [userName]),
                  ),
                ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, List<_i8.UserModel>>>(
                    this,
                    Invocation.method(#getBlockedList, [userName]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i8.UserModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> updateProfileBanner(
    String? userId,
    String? mediaId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfileBanner, [userId, mediaId]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#updateProfileBanner, [userId, mediaId]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#updateProfileBanner, [userId, mediaId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> updateProfilePhoto(
    String? userId,
    String? mediaId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfilePhoto, [userId, mediaId]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#updateProfilePhoto, [userId, mediaId]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#updateProfilePhoto, [userId, mediaId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i9.ProfileTweetModel>>>
  getProfilePosts(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#getProfilePosts, [username]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i9.ProfileTweetModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i9.ProfileTweetModel>>
                  >(this, Invocation.method(#getProfilePosts, [username])),
                ),
            returnValueForMissingStub:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i9.ProfileTweetModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i9.ProfileTweetModel>>
                  >(this, Invocation.method(#getProfilePosts, [username])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i9.ProfileTweetModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i9.ProfileTweetModel>>>
  getProfileLikes(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileLikes, [username]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i9.ProfileTweetModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i9.ProfileTweetModel>>
                  >(this, Invocation.method(#getProfileLikes, [username])),
                ),
            returnValueForMissingStub:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i9.ProfileTweetModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i9.ProfileTweetModel>>
                  >(this, Invocation.method(#getProfileLikes, [username])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i9.ProfileTweetModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> createTweet(
    _i10.CreateTweetModel? createTweetModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createTweet, [createTweetModel]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#createTweet, [createTweetModel]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#createTweet, [createTweetModel]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i11.TweetReplyModel>>>
  getTweetReplies(String? tweetId) =>
      (super.noSuchMethod(
            Invocation.method(#getTweetReplies, [tweetId]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i11.TweetReplyModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i11.TweetReplyModel>>
                  >(this, Invocation.method(#getTweetReplies, [tweetId])),
                ),
            returnValueForMissingStub:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i11.TweetReplyModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i11.TweetReplyModel>>
                  >(this, Invocation.method(#getTweetReplies, [tweetId])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i11.TweetReplyModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> deleteTweet(String? tweetId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTweet, [tweetId]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#deleteTweet, [tweetId]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#deleteTweet, [tweetId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i12.SearchUserModel>>>
  profileCurrentSearch(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#profileCurrentSearch, [query]),
            returnValue:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i12.SearchUserModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i12.SearchUserModel>>
                  >(this, Invocation.method(#profileCurrentSearch, [query])),
                ),
            returnValueForMissingStub:
                _i3.Future<
                  _i4.Either<_i5.Failure, List<_i12.SearchUserModel>>
                >.value(
                  _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i12.SearchUserModel>>
                  >(this, Invocation.method(#profileCurrentSearch, [query])),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, List<_i12.SearchUserModel>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> likeTweet(String? tweetId) =>
      (super.noSuchMethod(
            Invocation.method(#likeTweet, [tweetId]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#likeTweet, [tweetId]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#likeTweet, [tweetId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> unLikeTweet(String? tweetId) =>
      (super.noSuchMethod(
            Invocation.method(#unLikeTweet, [tweetId]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#unLikeTweet, [tweetId]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#unLikeTweet, [tweetId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> saveTweet(String? tweetId) =>
      (super.noSuchMethod(
            Invocation.method(#saveTweet, [tweetId]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#saveTweet, [tweetId]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#saveTweet, [tweetId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> unSaveTweet(String? tweetId) =>
      (super.noSuchMethod(
            Invocation.method(#unSaveTweet, [tweetId]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#unSaveTweet, [tweetId]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#unSaveTweet, [tweetId]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> replyOnTweet(
    String? tweetId,
    _i13.CreateReplyModel? createreplyModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#replyOnTweet, [tweetId, createreplyModel]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#replyOnTweet, [tweetId, createreplyModel]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#replyOnTweet, [
                      tweetId,
                      createreplyModel,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> changeEmailProfile(
    String? newEmail,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changeEmailProfile, [newEmail]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#changeEmailProfile, [newEmail]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#changeEmailProfile, [newEmail]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> verifyChangeEmailProfile(
    String? newEmail,
    String? code,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyChangeEmailProfile, [newEmail, code]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#verifyChangeEmailProfile, [newEmail, code]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#verifyChangeEmailProfile, [
                      newEmail,
                      code,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> changePasswordProfile(
    String? oldPassword,
    String? newPassword,
    String? confirmNewPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePasswordProfile, [
              oldPassword,
              newPassword,
              confirmNewPassword,
            ]),
            returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
              _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                this,
                Invocation.method(#changePasswordProfile, [
                  oldPassword,
                  newPassword,
                  confirmNewPassword,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i4.Either<_i5.Failure, void>>.value(
                  _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
                    this,
                    Invocation.method(#changePasswordProfile, [
                      oldPassword,
                      newPassword,
                      confirmNewPassword,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i4.Either<_i5.Failure, void>>);
}
