// Mocks generated by Mockito 5.4.6 from annotations
// in lite_x/test/features/search/providers/search_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:lite_x/features/home/models/tweet_model.dart' as _i3;
import 'package:lite_x/features/search/data/search_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserSearchPage_0 extends _i1.SmartFake
    implements _i2.UserSearchPage {
  _FakeUserSearchPage_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTweetSearchPage_1 extends _i1.SmartFake
    implements _i2.TweetSearchPage {
  _FakeTweetSearchPage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTweetModel_2 extends _i1.SmartFake implements _i3.TweetModel {
  _FakeTweetModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SearchRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchRepository extends _i1.Mock implements _i2.SearchRepository {
  MockSearchRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserSearchPage> searchUsers(
    String? query, {
    String? cursor,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchUsers,
              [query],
              {#cursor: cursor, #limit: limit},
            ),
            returnValue: _i4.Future<_i2.UserSearchPage>.value(
              _FakeUserSearchPage_0(
                this,
                Invocation.method(
                  #searchUsers,
                  [query],
                  {#cursor: cursor, #limit: limit},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.UserSearchPage>);

  @override
  _i4.Future<_i2.TweetSearchPage> searchTweets({
    required String? query,
    required _i2.SearchTab? tab,
    String? peopleFilter = 'ANYONE',
    String? cursor,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchTweets, [], {
              #query: query,
              #tab: tab,
              #peopleFilter: peopleFilter,
              #cursor: cursor,
              #limit: limit,
            }),
            returnValue: _i4.Future<_i2.TweetSearchPage>.value(
              _FakeTweetSearchPage_1(
                this,
                Invocation.method(#searchTweets, [], {
                  #query: query,
                  #tab: tab,
                  #peopleFilter: peopleFilter,
                  #cursor: cursor,
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.TweetSearchPage>);

  @override
  _i4.Future<_i3.TweetModel> toggleLike(
    String? tweetId,
    bool? isCurrentlyLiked,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleLike, [tweetId, isCurrentlyLiked]),
            returnValue: _i4.Future<_i3.TweetModel>.value(
              _FakeTweetModel_2(
                this,
                Invocation.method(#toggleLike, [tweetId, isCurrentlyLiked]),
              ),
            ),
          )
          as _i4.Future<_i3.TweetModel>);
}
